version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      typescript-eslint:
        patterns:
        - "@typescript-eslint/*"
      testing-library:
        patterns:
        - "@testing-library/*"
      graphql-codegen:
        patterns:
        - "@graphql-codegen/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
