// TODO: put into API
export const Zones: { [key: number]: string } = {
  1: 'Marshes of Madness',
  2: 'Badlands',
  3: 'Black Crag',
  4: "Butcher's Pass",
  5: 'Thunder Mountain',
  6: 'Ekrund',
  7: 'Barak Varr',
  8: 'Black Fire Pass',
  9: 'Kadrin Valley',
  10: 'Stonewatch',
  11: 'Mt Bloodhorn',
  12: 'Dangerous Territory - Bloodhorn South',
  13: 'Dangerous Territory - Marshes West',
  14: 'Dangerous Territory - Barak Varr East',
  15: 'Dangerous Territory - Marshes South',
  16: 'Dangerous Territory - Kadrin-Blackfire Scenery',
  17: 'Dangerous Territory - Kadrin East',
  18: 'Dangerous Territory - Karaz-a-Karak West',
  19: 'Dangerous Territory - Karaz-a-Karak East',
  20: 'Dangerous Territory - Eight Peaks East',
  21: 'Dangerous Territory - Eight Peaks West',
  22: 'Dangerous Territory - Blackfire West',
  23: 'Dangerous Territory - NorthWest Blackfire',
  24: 'Dangerous Territory - North Blackfire',
  25: 'Dangerous Territory - Marshes East',
  26: 'TM West - Cinderfall',
  27: 'TM East - Death Peak',
  28: 'Bloodhorn North',
  30: 'Gates of Ekrund',
  31: 'Mourkain Temple',
  32: 'Ironclad',
  33: 'Doomfist Crater',
  34: 'Thunder Valley',
  36: 'Kadrin Valley Pass',
  37: 'Black Crag Keep',
  38: 'Black Fire Basin',
  39: "Logrin's Forge",
  41: 'Altdorf War Quarters',
  42: 'The Undercroft',
  43: 'Gromril Crossing',
  44: 'Howling Gorge',
  46: 'EPG',
  48: 'KG',
  50: "Hunter's Vale",
  51: 'Bloodborn Keep',
  52: "Bugman's Brewery",
  60: 'Mount Gunbad Realm 1',
  61: 'Karak Eight Peaks',
  62: 'Karaz-A-Karak',
  63: 'Gunbad Nursery',
  64: 'Gunbad Lab',
  65: 'Squig Boss',
  66: 'Gunbad Barracks',
  67: 'Karak Eight Peaks - Contested',
  68: 'Karaz-A-Karak City Zone - Contested',
  69: 'Mount Gunbad - Instanced Launch',
  70: 'Dangerous Territory - Barak Varr North',
  71: 'Dangerous Territory - Barak Varr West',
  72: 'Dangerous Territory - Bloodhorn East',
  73: 'Dangerous Territory - Bloodhorn NorthEast',
  74: 'Dangerous Territory - Barak Varr NorthWest',
  75: 'Dangerous Territory - Badlands West',
  76: 'Dangerous Territory - Badlands South',
  77: 'Dangerous Territory - Black Crag West',
  78: 'Dangerous Territory - Black Crag East',
  79: 'Dangerous Territory - Badlands Southwest',
  82: 'Dangerous Territory - Barak Varr NorthEast',
  83: 'Dangerous Territory - Marshes SouthWest',
  84: 'Dangerous Territory - Marshes SouthEast',
  85: 'Dangerous Territory - Ekrund South',
  86: 'Dangerous Territory - Ekrund West',
  87: 'Dangerous Territory - Black Fire East',
  88: 'Dangerous Territory - Badlands East',
  89: 'Dangerous Territory - Blackfire NE',
  90: 'Dangerous Territory - Badlands SE',
  96: 'Karak Eight Peaks Sublevel',
  97: 'Karaz-A-Karak Sublevel',
  100: 'Norsca',
  101: 'Troll Country',
  102: 'High Pass',
  103: 'Chaos Wastes',
  104: 'The Maw',
  105: 'Praag',
  106: 'Barony of Nordland',
  107: 'Ostland',
  108: 'Talabecland',
  109: 'Reikland',
  110: 'Reikwald',
  111: 'Dangerous Territory - Troll Country West',
  112: 'Dangerous Territory - Troll Country East',
  113: 'Dangerous Territory - Troll Country North',
  114: 'Dangerous Territory - Troll Country Northeast',
  115: 'Dangerous Territory - Troll Country Northwest',
  116: 'Dangerous Territory - High Pass East',
  117: 'Chaos Wastes East - Outer Dark',
  118: 'Dangerous Territory - Chaos Wastes West',
  120: 'West Praag',
  121: 'Dangerous Territory - West High Pass',
  122: 'Dangerous Territory - Northwest High Pass',
  123: 'Dangerous Territory - North High Pass',
  124: 'Dangerous Territory - Northeast High Pass',
  125: 'Dangerous Territory - East Norsca',
  126: 'Dangerous Territory - Talabec East',
  127: 'Dangerous Territory - East Praag Scenery',
  128: 'Dangerous Territory - East Nordland',
  129: 'Dangerous Territroy - South Nordland',
  130: 'Nordenwatch',
  131: 'Stone Troll Crossing',
  132: 'Talabec Dam',
  133: 'Maw of Madness',
  134: 'Reikland Hills',
  135: 'Twisting Tower',
  136: 'Battle for Praag',
  137: 'Grovod Caverns',
  138: 'Reikland Factory',
  139: 'High Pass Cemetery',
  140: 'New Elf Scenario',
  142: 'Dangerous Territory - Reikland West',
  143: 'Dangerous Territory - Reikland East',
  144: 'Dangerous Territory - West Reikwald',
  145: 'Dangerous Territory - East Reikwald',
  146: 'Dangerous Territory - West Maw',
  147: 'Dangerous Territory - East Maw',
  150: 'Dangerous Territory - Ostland SW',
  151: 'Dangerous Territory - Ostland SE',
  152: 'The Sewers of Altdorf: Wing 1 - Sewers 2',
  153: 'The Sewers of Altdorf: Wing 2 - Sewers 3',
  154: 'Warpblade 2',
  155: 'Sacellum Dungeons: West Wing - Sacellum 2',
  156: 'Sacellum Dungeons: East Wing -  Sacellum 3',
  157: 'Sigmar Temple',
  158: 'The Monolith',
  159: 'Sacellum',
  160: 'Bastion Stair',
  161: 'Inevitable City',
  162: 'Altdorf',
  163: "Bastion Stair - Thar'Ignan",
  164: 'Bastion Stair - Lord Slaurith',
  165: 'Bastion Stair - Kaarn the Vanquisher',
  166: "Bastion Stair - Skull Lord Var'Ithrok",
  167: 'Inevitable City Contested',
  168: 'Altdorf Contested',
  169: 'The Sewers of Altdorf: Wing 3 - Sewers',
  170: 'Altdorf Palace',
  171: 'The Screaming Cat',
  172: 'The Eternal Citadel',
  173: 'Sacellum Dungeons: South Wing - Sacellum',
  174: 'The Elysium',
  175: 'Winds of Chaos',
  176: 'Temple Crypts',
  177: 'Skaven Tunnels',
  178: 'The Viper Pit',
  179: 'Tomb of the Vulture Lord - RvR Dungeon',
  180: 'Dangerous Territory - Norsca Ocean',
  181: 'Dangerous Territory - Nordland Ocean',
  182: 'Dangerous Territory - Talabecland West',
  183: 'Dangerous Territory - Talabecland SouthWest',
  184: 'Dangerous Territory - Talabecland South',
  185: 'Dangerous Territory - Talabecland SouthEast',
  186: 'Dangerous Territory - Far West Praag',
  187: 'Dangerous Territory - Far Southwest Praag',
  188: 'Dangerous Territory - Far Northwest Praag',
  190: 'Bright Wizard College',
  191: 'Necropolis of Zandri - RvR Terrain - Tomb Kings',
  192: 'Dangerous Territory - Ostland West',
  193: 'Dangerous Territory - Ostland East',
  194: 'Dangerous Territory - Ostland South',
  195: 'Bloodwrought Enclave',
  196: 'Bilerot Burrow',
  197: 'The Bright Wizard College',
  198: "Sigmar's Hammer",
  199: 'Dangerous Territory - Tomb Kings North Scenery',
  200: 'The Blighted Isle',
  201: 'Shadowlands',
  202: 'Avelorn',
  203: 'Caledor',
  204: 'Fell Landing',
  205: 'Dragonwake',
  206: 'Chrace',
  207: 'Ellyrion',
  208: 'Saphery',
  209: 'Eataine',
  210: 'Shining Way',
  211: 'Dangerous Territory - West Blighted Isle',
  212: 'Dangerous Territory - Northwest Blighted Isle',
  213: 'Dangerous Territory - The Great Ocean',
  214: 'Dangerous Territory - Northeast Blighted Isle',
  215: 'Dangerous Territory - East Blighted Isle',
  216: 'Dangerous Territory - West Chrace',
  217: 'Dangerous Territory - East Chrace',
  218: 'Dangerous Territory - North Caledor',
  219: 'Dangerous Territory - Caledor South',
  220: 'Isle of the Dead',
  221: 'Dangerous Territory - Shadowlands North',
  222: 'Dangerous Territory - West Avelorn',
  223: 'Dangerous Territory - East Avelorn',
  224: 'Dangerous Territory - North Avelorn',
  225: 'Dangerous Territory - Shadowlands NorthEast',
  226: 'Dangerous Territory - Shadowlands NorthWest',
  227: 'Dangerous Territory - Shadowlands East',
  228: 'Dangerous Territory - Shadowlands West',
  229: 'Dangerous Territory - South Chrace',
  230: "Khaine's Embrace",
  231: 'Phoenix Gate',
  232: 'Tor Anroc',
  233: 'Scenario - Unk',
  234: "Serpent's Passage",
  235: "Dragon's Bane",
  236: 'Temple of Isha',
  237: 'Caledor Woods',
  238: 'Blood of the Black Cairn',
  241: 'Tomb of the Stars - RvR Lair 1',
  242: 'Tomb of the Moon - RvR Lair 2',
  243: 'Tomb of the Sky - RvR Lair 3',
  244: 'Tomb of the Sun - RvR Lair 4',
  245: 'Dangerous Territory - West Sea',
  246: 'Dangerous Territory - Northwest Sea',
  247: 'Dangerous Territory - North Sea',
  248: 'Dangerous Territory - Northeast Sea',
  249: 'Dangerous Territory - East Sea',
  260: 'Lost Vale',
  274: 'The Pyramid of Settra',
  275: 'Dangerous Territory - North Fell Landing',
  276: 'Dangerous Territory - South Fell Landing',
  277: 'Dangerous Territory - North Shining Way',
  278: 'Dangerous Territory - South Shining Way',
  279: 'Dangerous Territory - South Dragonwake',
  280: 'Dangerous Territory - West  Ellyrion',
  281: 'Dangerous Territory - Southwest Ellyrion',
  282: 'Dangerous Territory - South Ellyrion',
  283: 'Dangerous Territory - Southeast Ellyrion',
  284: 'Dangerous Territory - East Ellyrion',
  285: 'Dangerous Territory - West Saphery',
  286: 'Dangerous Territory - SW Saphery',
  287: 'Dangerous Territory - South Saphery',
  288: 'Dangerous Territory - SE Saphery',
  289: 'Dangerous Territory - East Saphery',
  290: 'Dangerous Territory - The Inner Sea',
  291: 'Dangerous Territory - North Eataine',
  292: 'Dangerous Territory - South Eataine',
  303: 'Dangerous Territory - East TK Scenery',
  304: 'Dangerous Terrirory - West TK Scenery',
  306: 'Dangerous Territory - South TK Scenery',
  307: 'Dangerous Territory - SW TK Scenery',
  410: "Thanquuol's Incursion",
  411: 'College Of Corruption',
  413: "Garden of Qu'aph",
};

export const Scenarios: { [key: number]: string } = {
  2000: 'Gates of Ekrund',
  2001: 'Mourkain Temple',
  2002: 'Black Fire Basin',
  2003: 'Kadrin Valley Pass',
  2004: 'Gromril Crossing',
  2005: 'Thunder Valley',
  2006: "Logrin's Forge",
  2007: 'Black Crag Keep',
  2008: 'Howling Gorge',
  2011: 'Doomfist Crater',
  2012: 'Altdorf War Quarter',
  2013: 'The Undercroft',
  2015: 'The Ironclad',
  2051: 'Mourkain Temple (Ranked Solo)',
  2052: 'Mourkain Temple (Ranked)',
  2053: 'Black Fire Basin (Ranked Solo)',
  2054: 'Black Fire Basin (Ranked)',
  2100: 'Nordenwatch',
  2101: 'Stonetroll Crossing',
  2102: 'Talabec Dam',
  2103: 'High Pass Cemetery',
  2104: 'Maw of Madness',
  2105: 'Twisting Tower',
  2106: 'Battle For Praag',
  2107: 'Grovod Caverns',
  2108: 'Reikland Factory',
  2109: 'Reikland Hills',
  2110: 'The Inevitable City',
  2111: 'Altdorf',
  2122: 'The Sacellum Arena',
  2123: 'The Eternal Citadel',
  2136: 'College of Corruption',
  2151: "Thanquol's Stand: Ratnarök",
  2152: 'Maw of Madness (Ranked Solo)',
  2153: 'Maw of Madness (Ranked)',
  2154: 'Reikland Hills (Ranked Solo)',
  2155: 'Reikland Hills (Ranked)',
  2156: 'Talabec Dam (Ranked Solo)',
  2157: 'Talabec Dam (Ranked)',
  2158: 'Daemonball Rally',
  2200: "Khaine's Embrace",
  2201: 'Phoenix Gate',
  2202: 'Tor Anroc',
  2203: 'Lost Temple of Isha',
  2204: "Serpent's Passage",
  2205: "Dragon's Bane",
  2206: 'Blood of the Black Cairn',
  2207: 'Caledor Woods',
  2251: 'Caledor Woods (Ranked Solo)',
  2252: 'Caledor Woods (Ranked)',
  2253: 'Phoenix Gate (Ranked Solo)',
  2254: 'Phoenix Gate (Ranked)',
  3000: 'Ranked Solo',
  3001: 'Ranked',
  3002: '6v6 Challenge ',
};
